### ISSUE TITLE
Processing request with an empty Content-Type header causes ArgumentNullException when accessing that header or enumerating all headers

### ISSUE THREAD

**Issue by MHHenriksen** [aspnet/HttpSysServer#420] opened 2017-12-06 14:20 UTC
Tested with Microsoft.AspNetCore.Server.HttpSys version 2.0.2 on Windows 10 Fall Creator's Update
Steps to reproduce:

1. `dotnet new webapi` (using .Net Core SDK 2.0.*)
2. Optionally add a specific dependency to HttpSys 2.0.2
3. `dotnet restore`
4. In Program.cs, add UseHttpSys() in the host builder chain
5. `dotnet run`
6. POST http://localhost:5000/api/values, set header `Content-Type` without a value

This will give a 500 response, since first the Model Binder throws when checking if the request is a form, and then the developer exception page throws when enumerating the request headers.

The log should show both stack traces. They have the top part in common:
```
System.ArgumentNullException: Array cannot be null.
Parameter name: chars
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount)
   at Microsoft.AspNetCore.Server.HttpSys.HeaderEncoding.GetString(SByte* pBytes, Int32 byteCount)
   at Microsoft.AspNetCore.Server.HttpSys.NativeRequestContext.GetKnownHeader(HttpSysRequestHeader header)
   at Microsoft.AspNetCore.Server.HttpSys.RequestHeaders.get_ContentType()
```

It looks like the problem is on https://github.com/aspnet/HttpSysServer/blob/2.0.2/src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/HeaderEncoding.cs#L21 where this is happening: https://stackoverflow.com/a/17091802/1246739 i.e. pinning an empty array is implementation defined, and in this case we're getting a null pointer.

So one solution is to have a special case for the input being empty there.

**Comment by MHHenriksen** [comment] 2017-12-06 15:33
If I were to make a pull request with a fix, which branch/tag/revision should I base it on?

**Comment by Tratcher** [comment] 2017-12-06 16:20
This is a duplicate of https://github.com/aspnet/HttpSysServer/issues/381

**Closed by Tratcher** 2017-12-06 16:20 UTC
